# Generated by Django 3.2.4 on 2021-06-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('S1', 'Some service #1'), ('S2', 'Some service #2'), ('S3', 'Some service #3'), ('S4', 'Some service #4'), ('S5', 'Some service #5')], max_length=2)),
                ('masters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('CLD', 'Appointment is canceled'), ('PDG', 'Appointment is in progress'), ('CPD', 'Appointment is completed'), ('PLD', 'Appointment is planned')], default='PLD', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_client', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_master', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.service')),
            ],
        ),
    ]
