# Generated by Django 3.2.4 on 2021-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210624_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(to='appointments.Master'),
        ),
    ]
