# Generated by Django 3.2.4 on 2021-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedulePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('appointment_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='work_schedule_parts',
            field=models.ManyToManyField(null=True, to='appointments.WorkSchedulePart'),
        ),
    ]
